config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "sessions#index", as: :index

  get "/privacy", to: static("privacy.html")
  get "/terms", to: static("terms.html")
  get "/admin_help", to: static("admin_help.html")
  get "/volunteer_help", to: static("volunteer_help.html")
  get "/dev_updates", to: static("dev_updates.html")
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  get "my_activity", to: "sessions#my_activity"

  get "signup", to: "users#signup"
  post "create_public_user", to: "users#create_public_user"

  get "reconcile_item_search", to: "items#reconcile_search"
  get "item_search_form", to: "items#search_form"
  get "index_item_search", to: "items#index_search"
  get "unverified_item_search", to: "items#unverified_search"
  get "uncategorized_item_search", to: "items#uncategorized_search"
  get "packed_item_search", to: "items#packed_search"
  get "reconcile_unverified", to: "reconcile_items#unverified"
  get "reconcile_uncategorized", to: "reconcile_items#uncategorized"
  get "reconcile_flagged", to: "reconcile_items#flagged"
  get "reconcile/:id", to: "reconcile_items#start", as: :reconcile_start
  post "reconcile/:id", to: "reconcile_items#confirm", as: :reconcile_confirm
  post "reconcile/:id/execute_reconcile", to: "reconcile_items#execute", as: :execute_reconcile
  get "reconcile/:id/item_instances", to: "reconcile_items#item_instances", as: :item_instances
  post "find_box", to: "boxes#find"
  post "find_pallet", to: "pallets#find"
  post "mass_action", to: "mass_actions#mass_action"
  get "all_received_items", to: "packed_items#all_received_items"
  get "received_categories", to: "packed_items#received_categories"
  get "received_categories/:id/received_category_items", to: "packed_items#received_category_items", as: :received_category_items
  get "received_category_items/:id/received_item_locations", to: "packed_items#received_item_locations", as: :received_item_locations
  get "received_categories/uncategorized", to: "packed_items#received_uncategorized_items", as: :received_uncategorized_items
  post "received_categories/unpack_selected", to: "packed_items#unpack_selected"

  resources :unpacking_events, only: %i[index update]
  resources :hospital_exports, only: :create
  resources :shipment_exports, only: :create
  resources :unpacking_events_exports, only: :create
  resources :categories
  resources :items
  resources :users do
    member do
      patch :change_password
    end
  end
  resources :warehouses
  resources :hospitals
  resources :packed_items, only: :index
  resources :staged_items
  post "staged_item_add_with_item", to: "staged_items#add_with_item"
  resources :warehoused_items
  post "warehoused_item_add_with_item", to: "warehoused_items#add_with_item"
  post "boxes/:id/unpack_all", to: "boxes#unpack_all", as: "boxes_unpack_all"
  post "pallets/:id/unpack_all", to: "pallets#unpack_all", as: "pallets_unpack_all"

  concern :boxable_items do
    resources :boxes do
      get "duplicate", to: "boxes#duplicate"
      post "add_with_item", to: "box_items#add_with_item"
      resources :box_items, except: %i[show edit new] do
        resources :box_unpacking_events, only: %i[create destroy]
      end
    end
  end

  concern :palletable_items do
    resources :pallets do
      post "add_with_item", to: "pallet_items#add_with_item"
      resources :pallet_items, except: %i[show edit new] do
        resources :pallet_unpacking_events, only: %i[create destroy]
      end
      concerns :boxable_items
    end
  end

  concern :containable_items do
    resources :containers do
      post "add_with_item", to: "container_items#add_with_item"
      resources :container_items, except: %i[show edit new] do
        resources :container_unpacking_events, only: %i[create destroy]
      end
      concerns :palletable_items
    end
  end

  concerns :boxable_items
  concerns :palletable_items
  concerns :containable_items
  resources :shipments do
    concerns :containable_items
  end

  # match '*unmatched', to: redirect('/404'), via: :all
end

app/models/box.rb
# frozen_string_literal: true

class Box < ApplicationRecord
  STATUSES = [
    WAREHOUSED = "Warehoused",
    STAGED = "Staged",
    IN_PROGRESS = "In Progress",
    COMPLETE = "Complete",
    RECEIVED = "Received",
    ARCHIVED = "Archived"
  ].freeze

  belongs_to :user, optional: false
  belongs_to :container, optional: true
  belongs_to :pallet, optional: true

  has_many :box_items, class_name: "PackedItem", dependent: :destroy
  has_many :items, through: :box_items

  accepts_nested_attributes_for :box_items, allow_destroy: true, reject_if: ->(x) { x[:quantity].blank? }

  scope :assigned, -> { where("pallet_id IS NOT NULL OR container_id IS NOT NULL") }
  scope :staged, -> { left_outer_joins(:pallet).where("boxes.status = ? OR pallets.status = ?", STAGED, STAGED) }
  scope :in_progress, -> { where(status: IN_PROGRESS) }
  scope :warehoused, -> { left_outer_joins(:pallet).where("boxes.status = ? OR pallets.status = ?", WAREHOUSED, WAREHOUSED) }
  scope :reassignable, -> { where(status: [WAREHOUSED, STAGED, IN_PROGRESS]) }

  validates :name, :custom_uid, :user, presence: true
  validates :custom_uid, :name, uniqueness: true # rubocop:disable Rails/UniqueValidationWithoutIndex
  validates :status, inclusion: { in: STATUSES }

  paginates_per 35

  after_initialize :set_defaults, if: :new_record?

  before_validation do
    if will_save_change_to_pallet_id? && pallet
      self.container = nil
    end
    if will_save_change_to_container_id? && container
      self.pallet = nil
    end
  end

  before_save do
    orphan_box if status_will_change_to_warehoused_or_staged?
    adopt_status if adopting_by_parent?
  end

  after_save do
    cascade_packed_items_location if saved_change_to_container_id || saved_change_to_pallet_id
    cascade_statuses if saved_change_to_status?
  end

  STATUSES.each do |stat|
    define_method("#{stat.parameterize(separator: "_")}?") do
      status == stat
    end
  end

  def shipment
    parent&.shipment
  end

  def parent
    container || pallet
  end

  def orphanable_status?
    status_will_change_to_warehoused_or_staged? && !parent&.status&.in?([ARCHIVED, WAREHOUSED, STAGED])
  end

  def adopting_by_parent?
    (pallet_id_change_to_be_saved&.first.nil? && container_id_change_to_be_saved&.first.nil?) &&
      (staged? || warehoused?) && !will_save_change_to_status?
  end

  private

  def status_will_change_to_warehoused_or_staged?
    status_change_to_be_saved&.last.in?([WAREHOUSED, STAGED])
  end

  def adopt_status
    return unless parent

    self.status = parent.status
  end

  def orphan_box
    self.container_id = nil
    self.pallet_id = nil
  end

  # TODO: Move these to a service
  def cascade_packed_items_location
    box_items.each(&:save!)
  end

  def cascade_statuses
    box_items.where.not(status: status).find_each { |bi| bi.update(status: status) }
  end

  def set_defaults
    cid = Box.maximum(:custom_uid).to_i + 1
    name = "BOX-#{cid}"
    self.name = name
    self.custom_uid = cid
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  STATUSES = %w[Active Deactivated].freeze
  ROLES = %w[Volunteer Shipping\ Manager Admin Receiving\ Manager].freeze

  belongs_to :warehouse, optional: true

  has_many :shipments
  has_many :containers
  has_many :container_items, through: :containers
  has_many :pallets
  has_many :pallet_items, through: :pallets
  has_many :boxes
  has_many :box_items, through: :boxes
  has_many :packed_items
  has_many :warehouses
  has_many :items

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true, on: %i[create update]  # rubocop:disable Rails/UniqueValidationWithoutIndex
  validates :phone, format: { with: /\A(?:\+?\d{1,3}\s*-?)?\(?(?:\d{3})?\)?[- ]?\d{3}[- ]?\d{4}\z/ }
  validates :first_name, :last_name, presence: true, on: %i[create update]
  validates :status, inclusion: { in: STATUSES }, on: %i[create update]
  validates :role, inclusion: { in: ROLES }, on: %i[create update]
  validates :password, presence: true, length: { minimum: 6 }, on: %i[create change_password]

  paginates_per 25

  def name
    "#{first_name} #{last_name}"
  end

  ROLES.each do |user_role|
    define_method("#{user_role.parameterize(separator: "_")}?") do
      role == user_role
    end
  end

  def active?
    status == "Active"
  end

  def selectable_statuses(klass)
    return klass::STATUSES if admin?

    klass::STATUSES - [klass::ARCHIVED]
  end

  def created_records?
    reflections = User.reflections.select do |_association_name, reflection|
      reflection.macro == :has_many
    end

    reflections.keys.map do |assoc|
      send(assoc).any?
    end.any?(true)
  end
end

app/controllers/boxes_controller.rb
# frozen_string_literal: true

class BoxesController < ApplicationController
  load_and_authorize_resource
  before_action :set_box, only: %i[show destroy update]

  def new
    @box = Box.new(
      container_id: params[:container_id],
      pallet_id: params[:pallet_id]
    )
  end

  def create
    box = Box.new(box_params.merge(user: current_user))

    if box.save
      redirect_to box_path(box), flash: { success: "Box created." }
    else
      redirect_to boxes_path,
        flash: { error: "Failed to create new box: #{box.errors.full_messages.to_sentence}" }
    end
  end

  def index
    @boxes = if params[:display]
      Box.includes(
          :box_items, :pallet, :container,
          pallet: [shipment: :receiving_warehouse],
          container: [shipment: :receiving_warehouse]
        )
        .accessible_by(current_ability)
        .send(params[:display])
        .order(custom_uid: :desc)
        .page params[:page]
    else
      Box.includes(
          :box_items, :pallet, :container,
          pallet: [shipment: :receiving_warehouse],
          container: [shipment: :receiving_warehouse]
        )
        .where.not(status: %w[Warehoused Staged])
        .accessible_by(current_ability)
        .order(custom_uid: :desc)
        .page params[:page]
    end

    @box_options = Box.reassignable
      .order(id: :desc)
      .pluck(:name, :id)
    @pallet_options = Pallet.reassignable
      .order(id: :desc)
      .pluck(:name, :id)
    @container_options = Container.in_progress
      .order(id: :desc)
      .pluck(:name, :id)
  end

  def show
    @staged_items = PackedItem.staged
      .order(created_at: :desc)
    @warehoused_items = PackedItem.warehoused
      .order(created_at: :desc)
    @box_options = Box.reassignable
      .order(id: :desc)
      .pluck(:name, :id)
    @pallet_options = Pallet.reassignable
      .order(id: :desc)
      .pluck(:name, :id)
    @container_options = Container.in_progress
      .order(id: :desc)
      .pluck(:name, :id)
  end

  def update
    if @box.update(box_params)
      redirect_to box_path(@box), flash: { success: "Box updated." }
    else
      redirect_to box_path(@box),
        flash: { error: "Failed to update box: #{@box.errors.full_messages.to_sentence}" }
    end
  end

  def destroy
    @box.destroy
    redirect_to boxes_path, flash: { success: "Box deleted." }
  end

  def find
    box = Box.accessible_by(current_ability)
      .find_by(custom_uid: box_params[:custom_uid])

    if box
      path = params[:button] == "info" ? box_path(box) : box_box_items_path(box)
      redirect_to path
    else
      redirect_to params[:redirect],
        flash: { error: "Box with custom ID #{box_params[:custom_uid]} not found." }
    end
  end

  def unpack_all
    # Definitely move this to a service :/
    if params[:hospital_id].blank?
      message = { error: "Please select a hospital/facility/clinic." }
    else
      @box.box_items.each do |bi|
        next if bi.remaining_quantity.zero?

        bi.unpacking_events
          .create(
            hospital_id: params[:hospital_id],
            notes: params[:notes],
            user: current_user,
            timestamp: params[:timestamp],
            quantity: bi.remaining_quantity
          )
      end

      message = { success: "#{@box.box_items.count} item(s) unpacked." }
    end

    redirect_back fallback_location: request.referer, flash: message
  end

  def duplicate
    box = Box.find(params[:box_id])
    deep_clone = params[:strategy] == "deep"
    pallet_id = box.pallet_id if deep_clone
    container_id = box.container_id if deep_clone

    ActiveRecord::Base.transaction do
      params[:duplication_count].to_i.times do
        new_box = Box.create(
          status: box.status,
          weight: box.weight,
          user_id: box.user_id,
          notes: box.notes,
          pallet_id: pallet_id,
          container_id: container_id
        )
        box.box_items.each do |bi|
          new_box.box_items.create(
            quantity: bi.quantity,
            remaining_quantity: bi.remaining_quantity,
            weight: bi.weight,
            expiry_date: bi.expiry_date,
            shipment_id: (bi.shipment_id if deep_clone),
            item_id: bi.item_id,
            user_id: bi.user_id,
            show_id: bi.show_id,
            status: bi.status
          )
        end
      end
    end

    redirect_back fallback_location: request.referer,
      flash: { success: "#{box.name} duplicated #{params[:duplication_count]} times." }
  end

  private

  def box_params
    params.require(:box)
      .permit(
        :name, :status, :notes, :custom_uid,
        :pallet_id, :container_id, :weight
      )
  end

  def set_box
    @box = Box.includes(box_items: :item).find(params[:id])
  end
end

app/views/boxes/_form.html.haml
- pallet_id = @box.pallet_id.presence || params[:pallet_id]
- container_id = @box.container_id.presence || params[:container_id]
- pallet_collection = @box.container.present? ? @box.container.pallets.accessible_by(current_ability) : Pallet.accessible_by(current_ability)
= form_for @box do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form-group
    %label Custom ID
    = f.number_field :custom_uid, min: 0, class: "form-control"
  .form-group
    = f.label :status
    = f.select :status, options_for_select(current_user.selectable_statuses(Box), @box.status), {}, { class: "form-control" }
  .form-group
    %label Weight (kg)
    = f.number_field :weight, min: 0, step: :any, class: "form-control"
  .form-group
    = f.label :notes
    = f.text_field :notes, class: "form-control"
  .form-group
    %label Pallet Assignment
    = f.select :pallet_id, options_from_collection_for_select(pallet_collection.order(id: :desc), :id, :name, pallet_id), { include_blank: "None" }, { class: "form-control", id: "pallet-assignment" }
  %hr
  %h5.text-center OR
  %hr
  .form-group
    %label Container Assignment
    = f.select :container_id, options_from_collection_for_select(Container.accessible_by(current_ability).order(id: :desc), :id, :name, container_id), { include_blank: "None" }, { class: "form-control", id: "container-assignment" }

  .btn-toolbar.list-toolbar
    - if @box.persisted?
      = delete_button(box_path(@box), "Are you sure you want to delete #{@box.name}? This cannot be reversed")
    = submit_button_responsive("Save")

app/views/boxes/_micro_table.html.haml
%table.table.table-striped.link-rows
  %thead
    %tr
      %th Custom ID
      %th Name
      %th Status
      - if can?(:create, Box)
        %th
  %tbody{id: table_id}
    - boxes.order(custom_uid: :desc).each do |box|
      %tr.filter-row
        %td
          = link_to box_path(box) do
            %p= box.custom_uid
        %td
          = link_to box_path(box) do
            %p= box.name
        %td
          = link_to box_path(box) do
            %p{class: "status-#{box.status.parameterize}"}= box.status
        - if can?(:create, Box)
          %td.mass-action-cell
            = check_box_tag "box_ids[]", box.id, false, class: "mass-action-table", form: "mass_action", id: "mass-action-box-#{box.id}"

app/views/boxes/_table.html.haml
- boxes ||= @boxes
%table.table.table-striped.table-hover.link-rows
  %thead
    %tr
      %th Custom ID
      %th Name
      %th Status
      %th.hidden-sm.hidden-xs Palletized?
      %th.hidden-xs Receiver
      %th.hidden-xs Created At
      - if can?(:create, Box)
        %th.mass-action-cell
  %tbody
    - boxes.each do |box|
      %tr
        %td
          = link_to box_path(box) do
            %p= box.custom_uid
        %td
          = link_to box_path(box) do
            %p= box.name
        %td
          = link_to box_path(box) do
            %p{class: "status-#{box.status.parameterize}"}= box.status
        %td.hidden-sm.hidden-xs
          = link_to box_path(box) do
            %p{class: (box.pallet.nil? ? "text-warning" : "text-success")}= box.pallet.nil? ? "No" : "Yes"
        %td.hidden-xs
          = link_to box_path(box) do
            %p= box&.shipment&.receiving_warehouse&.name
        %td.hidden-xs
          = link_to box_path(box) do
            %p= box.created_at.strftime("%Y-%m-%d")
        - if can?(:create, Box)
          %td.mass-action-cell
            = check_box_tag "box_ids[]", box.id, false, class: "mass-action-table", form: "mass_action", id: "mass-action-box-#{box.id}"

app/views/boxes/index.html.haml
- title = "#{params[:display].present? ? params[:display] + " " : "" }boxes"
.content
  .header
    %ul.breadcrumb
      %li
        = link_to "Home", index_path
      %li.active= title.titleize
    = render partial: "layouts/jump_to_modal"
    - if can? :create, Box
      = add_button(new_box_path, "Box", "fa-box-open")
    - if can? :manage, PackedItem
      = render partial: "layouts/mass_action_modal", locals: {name: title, redirect: boxes_path(display: params[:display]), record: nil}

  .main-content
    - if @boxes.any?
      - if params[:display] == "warehoused" || params[:display] == "staged"
        %h5
          Showing all <em>#{params[:display].titleize}</em> boxes and any boxes
          on <em>#{params[:display].titleize}</em> pallets.
      - elsif params[:display] == "in_progress"
        %h5 Showing all <em>In Progress</em> boxes and any boxes on <em>In Progress</em> pallets.

      - else
        %h5
          <em>Staged</em> and <em>Warehoused</em> boxes are not shown here
          and can be found in their respective menus.

      = render "table"
      = paginate @boxes, window: 2

    - else
      %h4.text-center
        No #{params[:display]}
        - if params[:display] == "warehoused"
          %i.fa.fa-fw.fa-clipboard-list
        - elsif params[:display] == "staged"
          %i.fa.fa-fw.fa-truck-loading
        boxes
        - if params[:display].nil?
          %i.fa.fa-fw.fa-box-open
        to display.

app/views/boxes/new.html.haml
.content
  .header
    %ul.breadcrumb
      %li
        = link_to "Home", index_path
      = present(@box).breadcrumbs
    = render partial: "layouts/jump_to_modal"
  .main-content
    .row
      .col-md-4
        - unless @box.persisted?
          %h5 Confirm new box information.
        = render partial: "form"

app/views/boxes/show.html.haml
.content
  .header
    %ul.breadcrumb
      %li
        = link_to "Home", index_path
      = present(@box).breadcrumbs
    = render partial: "layouts/jump_to_modal"
    - if can? :manage, Box
      = render partial: "layouts/edit_modal"
    - if can?(:read, PackedItem) || can?(:unpack_all, Box)
      = manage_button(box_box_items_path(@box), "Items", "fa-stethoscope")
    - if can?(:manage, PackedItem)
      = render partial: "layouts/mass_action_modal", locals: {name: @box.name, redirect: box_path(@box), record: @box}
      = render partial: "layouts/duplicate_modal"
    - if current_user.admin? || current_user.receiving_manager?
      = render partial: "layouts/boxes_unpack_all_modal"

  .main-content
    .row
      .col-md-5
        .row
          .col-xs-12
            %h5.text-muted Name
            %h4= @box.name
            %hr
          - if @box.notes.present?
            .col-xs-12
              %h5.text-muted Notes
              %h4= @box.notes
          .col-xs-6.col-sm-4.col-md-6
            %h6.text-muted Custom ID
            %h5= @box.custom_uid
          .col-xs-6.col-sm-4.col-md-6
            %h6.text-muted Status
            %h5{class: "status-#{@box.status.parameterize}"}= @box.status
          .col-xs-6.col-sm-4.col-md-6
            %h6.text-muted Weight (kg)
            %h5= @box.weight.to_f.round(4) || "N/A"
          .col-xs-6.col-sm-4.col-md-6
            %h6.text-muted Created By
            %h5= @box.user.name
          .col-xs-6.col-sm-4.col-md-6
            %h6.text-muted Created At
            %h5= @box.created_at.strftime("%Y-%m-%d")

      .col-md-7
        %br
        - present(@box) do |box|
          .panel.panel-default
            %a.panel-heading{data: {toggle: "collapse"}, href: "#location"}
              %i.fa.fa-map-marker-alt
              Location Details
            #location.collapse.in
              %table.table.list
                %tbody
                  %tr
                    %td
                      %p Warehouse
                    = box.warehouse_location
                  %tr
                    %td
                      %p Shipment
                    = box.shipment_location
                  %tr
                    %td
                      %p Container
                    = box.container_location
                  - unless box.container.present? && box.pallet.nil?
                    %tr
                      %td
                        %p Pallet
                      = box.pallet_location

        .panel.panel-default
          %a.panel-heading{class: (@box.box_items.count > 5 && "collapsed"), data: {toggle: "collapse"}, href: "#packed-items"}
            %i.fa.fa-stethoscope
            Boxed Items
            %span.label{class: @box.box_items.any? ? "label-success" : "label-warning"}= @box.box_items.size

          - if @box.box_items.any?
            #packed-items.collapse{class: (@box.box_items.count < 6 && "in")}
              = render partial: "layouts/table_quick_filter", locals: {placeholder: "Filter by name...", assoc: "packed-items"}
              = render partial: "packed_items/micro_table", locals: {packed_items: @box.box_items, assoc: "packed-items"}
              .close-collapse{data: {toggle: "collapse"}, href: "#packed-items"}
                %span Close
          - else
            #packed-items.collapse.panel-body
              %h5.text-center
                No packed items
                %i.fa.fa-stethoscope
                in this box
                %i.fa.fa-box-open

  - if (can? :manage, PackedItem) && (@staged_items.any? || @warehoused_items.any?)
    = render "layouts/mass_action_add", display: %i[items]