config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "sessions#index", as: :index

  get "/privacy", to: static("privacy.html")
  get "/terms", to: static("terms.html")
  get "/admin_help", to: static("admin_help.html")
  get "/volunteer_help", to: static("volunteer_help.html")
  get "/dev_updates", to: static("dev_updates.html")
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  get "my_activity", to: "sessions#my_activity"

  get "signup", to: "users#signup"
  post "create_public_user", to: "users#create_public_user"

  get "reconcile_item_search", to: "items#reconcile_search"
  get "item_search_form", to: "items#search_form"
  get "index_item_search", to: "items#index_search"
  get "unverified_item_search", to: "items#unverified_search"
  get "uncategorized_item_search", to: "items#uncategorized_search"
  get "packed_item_search", to: "items#packed_search"
  get "reconcile_unverified", to: "reconcile_items#unverified"
  get "reconcile_uncategorized", to: "reconcile_items#uncategorized"
  get "reconcile_flagged", to: "reconcile_items#flagged"
  get "reconcile/:id", to: "reconcile_items#start", as: :reconcile_start
  post "reconcile/:id", to: "reconcile_items#confirm", as: :reconcile_confirm
  post "reconcile/:id/execute_reconcile", to: "reconcile_items#execute", as: :execute_reconcile
  get "reconcile/:id/item_instances", to: "reconcile_items#item_instances", as: :item_instances
  post "find_box", to: "boxes#find"
  post "find_pallet", to: "pallets#find"
  post "mass_action", to: "mass_actions#mass_action"
  get "all_received_items", to: "packed_items#all_received_items"
  get "received_categories", to: "packed_items#received_categories"
  get "received_categories/:id/received_category_items", to: "packed_items#received_category_items", as: :received_category_items
  get "received_category_items/:id/received_item_locations", to: "packed_items#received_item_locations", as: :received_item_locations
  get "received_categories/uncategorized", to: "packed_items#received_uncategorized_items", as: :received_uncategorized_items
  post "received_categories/unpack_selected", to: "packed_items#unpack_selected"

  resources :unpacking_events, only: %i[index update]
  resources :hospital_exports, only: :create
  resources :shipment_exports, only: :create
  resources :unpacking_events_exports, only: :create
  resources :categories
  resources :items
  resources :users do
    member do
      patch :change_password
    end
  end
  resources :warehouses
  resources :hospitals
  resources :packed_items, only: :index
  resources :staged_items
  post "staged_item_add_with_item", to: "staged_items#add_with_item"
  resources :warehoused_items
  post "warehoused_item_add_with_item", to: "warehoused_items#add_with_item"
  post "boxes/:id/unpack_all", to: "boxes#unpack_all", as: "boxes_unpack_all"
  post "pallets/:id/unpack_all", to: "pallets#unpack_all", as: "pallets_unpack_all"

  concern :boxable_items do
    resources :boxes do
      get "duplicate", to: "boxes#duplicate"
      post "add_with_item", to: "box_items#add_with_item"
      resources :box_items, except: %i[show edit new] do
        resources :box_unpacking_events, only: %i[create destroy]
      end
    end
  end

  concern :palletable_items do
    resources :pallets do
      post "add_with_item", to: "pallet_items#add_with_item"
      resources :pallet_items, except: %i[show edit new] do
        resources :pallet_unpacking_events, only: %i[create destroy]
      end
      concerns :boxable_items
    end
  end

  concern :containable_items do
    resources :containers do
      post "add_with_item", to: "container_items#add_with_item"
      resources :container_items, except: %i[show edit new] do
        resources :container_unpacking_events, only: %i[create destroy]
      end
      concerns :palletable_items
    end
  end

  concerns :boxable_items
  concerns :palletable_items
  concerns :containable_items
  resources :shipments do
    concerns :containable_items
  end

  # match '*unmatched', to: redirect('/404'), via: :all
end

app/models/container.rb
# frozen_string_literal: true

class Container < ApplicationRecord
  STATUSES = [
    IN_PROGRESS = "In Progress",
    COMPLETE = "Complete",
    RECEIVED = "Received",
    ARCHIVED = "Archived"
  ].freeze

  belongs_to :user, optional: false
  belongs_to :shipment, optional: true

  has_many :boxes, dependent: :nullify
  has_many :box_items, through: :boxes
  has_many :pallets, dependent: :nullify
  has_many :pallet_items, through: :pallets
  has_many :pallet_boxes, through: :pallets, source: :boxes
  has_many :pallet_box_items, through: :pallet_boxes, source: :box_items
  has_many :container_items, class_name: "PackedItem", dependent: :destroy
  has_many :items, through: :container_items

  accepts_nested_attributes_for :container_items, allow_destroy: true, reject_if: ->(x) { x[:quantity].blank? }

  scope :staged, -> { where(shipment_id: nil) }
  scope :in_progress, -> { where(status: IN_PROGRESS) }

  validates :name, :custom_uid, :user, presence: true
  validates :custom_uid, :name, uniqueness: true # rubocop:disable Rails/UniqueValidationWithoutIndex
  validates :status, inclusion: { in: STATUSES }

  paginates_per 35

  after_save do
    cascade_statuses if saved_change_to_status && cascadable?
    cascade_packed_items_location if saved_change_to_shipment_id
  end

  after_initialize :set_defaults, if: :new_record?

  STATUSES.each do |stat|
    define_method("#{stat.parameterize(separator: "_")}?") do
      status == stat
    end
  end

  def cascadable?
    complete? || received? || archived?
  end

  private

  # TODO: Move these to a service
  def cascade_statuses
    boxes.where.not(status: status).find_each { |b| b.update(status: status) }
    pallets.where.not(status: status).find_each { |p| p.update(status: status) }
    container_items.where.not(status: status).find_each { |ci| ci.update(status: status) }
  end

  def cascade_packed_items_location
    container_items.each(&:save!)
    pallet_items.each(&:save!)
    pallet_box_items.each(&:save!)
    box_items.each(&:save!)
  end

  def set_defaults
    cid = Container.maximum(:custom_uid).to_i + 1
    name = "CONTAINER-#{cid}"
    self.name = name
    self.custom_uid = cid
    self.status = IN_PROGRESS
  end
end

app/controllers/containers_controller.rb
# frozen_string_literal: true

class ContainersController < ApplicationController
  load_and_authorize_resource
  before_action :set_container, only: %i[show destroy update]

  def new
    @container = Container.new(shipment_id: params[:shipment_id])
  end

  def create
    container = Container.new(container_params.merge(user: current_user))

    if container.save
      redirect_to container_path(container), flash: { success: "Container created." }
    else
      redirect_to containers_path,
        flash: { error: "Failed to create new container: #{container.errors.full_messages.to_sentence}" }
    end
  end

  def index
    @containers = if params[:display]
      Container.includes(shipment: :receiving_warehouse)
        .accessible_by(current_ability)
        .send(params[:display])
        .order(custom_uid: :desc)
        .page params[:page]
    else
      Container.includes(shipment: :receiving_warehouse)
        .accessible_by(current_ability)
        .order(custom_uid: :desc)
        .page params[:page]
    end
  end

  def show
    @staged_items = PackedItem.staged
      .order(created_at: :desc)
    @staged_boxes = Box.staged
      .order(custom_uid: :desc)
    @staged_pallets = Pallet.staged
      .order(custom_uid: :desc)
    @warehoused_items = PackedItem.warehoused
      .order(created_at: :desc)
    @warehoused_boxes = Box.warehoused
      .order(custom_uid: :desc)
    @warehoused_pallets = Pallet.warehoused
      .order(custom_uid: :desc)
    @box_options = Box.reassignable
      .order(id: :desc)
      .pluck(:name, :id)
    @pallet_options = Pallet.reassignable
      .order(id: :desc)
      .pluck(:name, :id)
    @container_options = Container.in_progress
      .order(id: :desc)
      .pluck(:name, :id)
  end

  def update
    if @container.update(container_params)
      redirect_to container_path(@container),
        flash: { success: "Container updated." }
    else
      redirect_to container_path(@container),
        flash: { error: "Failed to update container: #{@container.errors.full_messages.to_sentence}" }
    end
  end

  def destroy
    @container.destroy
    redirect_to containers_path, flash: { success: "Container deleted." }
  end

  private

  def container_params
    params.require(:container)
      .permit(:name, :status, :notes, :custom_uid, :shipment_id, :weight)
  end

  def set_container
    @container = Container.includes(
      :boxes, :pallets, :shipment, container_items: :item
    ).find(params[:id])
  end
end

app/views/containers/_form.html.haml
- shipment_id = @container.shipment_id.presence || params[:shipment_id]
= form_for @container do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form-group
    %label Custom ID
    = f.number_field :custom_uid, min: 0, class: "form-control"
  .form-group
    = f.label :status
    = f.select :status, options_for_select(current_user.selectable_statuses(Container), @container.status), {}, { class: "form-control", id: "status" }
  .form-group
    %label Weight (kg)
    = f.number_field :weight, min: 0, step: :any, class: "form-control"
  .form-group
    = f.label :notes
    = f.text_field :notes, class: "form-control"
  - if can? :reassign, Container
    .form-group
      %label Shipment Assignment
      = f.select :shipment_id, options_from_collection_for_select(Shipment.accessible_by(current_ability).order(id: :desc), :id, :name, shipment_id), { include_blank: "None" }, { class: "form-control", id: "shipment-assignment"}

  .btn-toolbar.list-toolbar
    - if @container.persisted?
      = delete_button(container_path(@container), "Are you sure you want to delete #{@container.name}? This cannot be reversed")
    = submit_button_responsive("Save")

app/views/containers/index.html.haml
.content
  .header
    %ul.breadcrumb
      %li
        = link_to "Home", index_path
      %li.active #{params[:display].present? ? params[:display].titleize + " " : "" }Containers
    = render partial: "layouts/jump_to_modal"
    - if can? :manage, Container
      = add_button(new_container_path, "Container", "fa-truck")
  .main-content
    %table.table.table-striped.table-hover.link-rows
      %thead
        %tr
          %th Custom ID
          %th Name
          %th Status
          %th.hidden-xs Receiver
          %th.hidden-xs Created At
      %tbody
        - @containers.each do |container|
          %tr
            %td
              = link_to container_path(container) do
                %p= container.custom_uid
            %td
              = link_to container_path(container) do
                %p= container.name
            %td
              = link_to container_path(container) do
                %p{class: "status-#{container.status.parameterize}"}= container.status
            %td.hidden-xs
              = link_to container_path(container) do
                %p= container.shipment&.receiving_warehouse&.name
            %td.hidden-xs
              = link_to container_path(container) do
                %p= container.created_at.strftime("%Y-%m-%d")

    = paginate @containers, window: 2

app/views/containers/new.html.haml
.content
  .header
    %ul.breadcrumb
      %li
        = link_to "Home", index_path
      = present(@container).breadcrumbs
    = render partial: "layouts/jump_to_modal"
  .main-content
    .row
      .col-md-4
        - unless @container.persisted?
          %h5 Confirm new container information.
        = render partial: "form"

app/views/containers/show.html.haml
.content
  .header
    %ul.breadcrumb
      %li
        = link_to "Home", index_path
      = present(@container).breadcrumbs
    = render partial: "layouts/jump_to_modal"
    - if can? :manage, Container
      = render partial: "layouts/edit_modal"
    - if can? :read, PackedItem
      = manage_button(container_container_items_path(@container), "Items", "fa-stethoscope")
    - if can? :manage, PackedItem
      = render partial: "layouts/mass_action_modal", locals: {name: @container.name, redirect: container_path(@container), record: @container}

  .main-content
    .row
      .col-md-5
        .row
          .col-xs-12
            %h5.text-muted Name
            %h4= @container.name
            %hr
          - if @container.notes.present?
            .col-xs-12
              %h6.text-muted Notes
              %h5= @container.notes
          .col-xs-6.col-sm-4.col-md-6
            %h6.text-muted Custom ID
            %h5= @container.custom_uid
          .col-xs-6.col-sm-4.col-md-6
            %h6.text-muted Status
            %h5{class: "status-#{@container.status.parameterize}"}= @container.status
          .col-xs-6.col-sm-4.col-md-6
            %h6.text-muted Weight (kg)
            %h5= @container.weight.to_f.round(4) || "N/A"
          .col-xs-6.col-sm-4.col-md-6
            %h6.text-muted Created By
            %h5= @container.user.name
          .col-xs-6.col-sm-4.col-md-6
            %h6.text-muted Created At
            %h5= @container.created_at.strftime("%Y-%m-%d")

      .col-md-7
        %br
        - present(@container) do |container|
          .panel.panel-default
            %a.panel-heading{data: {toggle: "collapse"}, href: "#location"}
              %i.fa.fa-map-marker-alt
              Location Details
            #location.collapse.in
              %table.table.list
                %tbody
                  %tr
                    %td
                      %p Warehouse
                    = container.warehouse_location
                  %tr
                    %td
                      %p Shipment
                    = container.shipment_location

        .panel.panel-default
          %a.panel-heading{data: {toggle: "collapse"}, href: "#pallets"}
            %i.fa.fa-pallet
            Pallets in this Container
            %span.label{class: @container.pallets.any? ? "label-success" : "label-warning"}= @container.pallets.size

          - if @container.pallets.any?
            #pallets.collapse
              = render partial: "layouts/table_quick_filter", locals: {placeholder: "Filter by custom ID...", assoc: "pallets"}
              = render partial: "pallets/micro_table", locals: {pallets: @container.pallets}
              .close-collapse{data: {toggle: "collapse"}, href: "#pallets"}
                %span Close
          - else
            #pallets.collapse.panel-body
              %h5.text-center
                No pallets
                %i.fa.fa-fw.fa-pallet
                in this
                %i.fa.fa-fw.fa-truck
                container

        .panel.panel-default
          %a.panel-heading{data: {toggle: "collapse"}, href: "#boxes"}
            %i.fa.fa-box-open
            Boxes in this Container
            %span.label{class: @container.boxes.any? ? "label-success" : "label-warning"}= @container.boxes.size

          - if @container.boxes.any?
            #boxes.collapse
              = render partial: "layouts/table_quick_filter", locals: {placeholder: "Filter by custom ID...", assoc: "boxes"}
              = render partial: "boxes/micro_table", locals: {boxes: @container.boxes, table_id: "filter-boxes-table"}
              .close-collapse{data: {toggle: "collapse"}, href: "#boxes"}
                %span Close
          - else
            #boxes.collapse.panel-body
              %h5.text-center
                No boxes
                %i.fa.fa-fw.fa-box-open
                in this
                %i.fa.fa-fw.fa-truck
                container

        .panel.panel-default
          %a.panel-heading.collapsed{class: (@container.container_items.count > 5 && "collapsed"),data: {toggle: "collapse"}, href: "#packed-items"}
            %i.fa.fa-stethoscope
            Containerized Items
            %span.label{class: @container.container_items.any? ? "label-success" : "label-warning"}= @container.container_items.size

          - if @container.container_items.any?
            #packed-items.collapse{class: (@container.container_items.count < 6 && "in")}
              = render partial: "layouts/table_quick_filter", locals: {placeholder: "Filter by name...", assoc: "packed-items"}
              = render partial: "packed_items/micro_table", locals: {packed_items: @container.container_items, assoc: "packed-items"}
              .close-collapse{data: {toggle: "collapse"}, href: "#packed-items"}
                %span Close
          - else
            #packed-items.collapse.panel-body
              %h5.text-center
                No packed items
                %i.fa.fa-fw.fa-stethoscope
                in this
                %i.fa.fa-fw.fa-truck
                container

  - if (can? :manage, PackedItem) && (@staged_items.any? || @staged_boxes.any? || @staged_pallets.any? || @warehoused_items.any? || @warehoused_boxes.any? || @warehoused_pallets.any?)
    = render "layouts/mass_action_add", display: %i[items boxes pallets]