config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "sessions#index", as: :index

  get "/privacy", to: static("privacy.html")
  get "/terms", to: static("terms.html")
  get "/admin_help", to: static("admin_help.html")
  get "/volunteer_help", to: static("volunteer_help.html")
  get "/dev_updates", to: static("dev_updates.html")
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  get "my_activity", to: "sessions#my_activity"

  get "signup", to: "users#signup"
  post "create_public_user", to: "users#create_public_user"

  get "reconcile_item_search", to: "items#reconcile_search"
  get "item_search_form", to: "items#search_form"
  get "index_item_search", to: "items#index_search"
  get "unverified_item_search", to: "items#unverified_search"
  get "uncategorized_item_search", to: "items#uncategorized_search"
  get "packed_item_search", to: "items#packed_search"
  get "reconcile_unverified", to: "reconcile_items#unverified"
  get "reconcile_uncategorized", to: "reconcile_items#uncategorized"
  get "reconcile_flagged", to: "reconcile_items#flagged"
  get "reconcile/:id", to: "reconcile_items#start", as: :reconcile_start
  post "reconcile/:id", to: "reconcile_items#confirm", as: :reconcile_confirm
  post "reconcile/:id/execute_reconcile", to: "reconcile_items#execute", as: :execute_reconcile
  get "reconcile/:id/item_instances", to: "reconcile_items#item_instances", as: :item_instances
  post "find_box", to: "boxes#find"
  post "find_pallet", to: "pallets#find"
  post "mass_action", to: "mass_actions#mass_action"
  get "all_received_items", to: "packed_items#all_received_items"
  get "received_categories", to: "packed_items#received_categories"
  get "received_categories/:id/received_category_items", to: "packed_items#received_category_items", as: :received_category_items
  get "received_category_items/:id/received_item_locations", to: "packed_items#received_item_locations", as: :received_item_locations
  get "received_categories/uncategorized", to: "packed_items#received_uncategorized_items", as: :received_uncategorized_items
  post "received_categories/unpack_selected", to: "packed_items#unpack_selected"

  resources :unpacking_events, only: %i[index update]
  resources :hospital_exports, only: :create
  resources :shipment_exports, only: :create
  resources :unpacking_events_exports, only: :create
  resources :categories
  resources :items
  resources :users do
    member do
      patch :change_password
    end
  end
  resources :warehouses
  resources :hospitals
  resources :packed_items, only: :index
  resources :staged_items
  post "staged_item_add_with_item", to: "staged_items#add_with_item"
  resources :warehoused_items
  post "warehoused_item_add_with_item", to: "warehoused_items#add_with_item"
  post "boxes/:id/unpack_all", to: "boxes#unpack_all", as: "boxes_unpack_all"
  post "pallets/:id/unpack_all", to: "pallets#unpack_all", as: "pallets_unpack_all"

  concern :boxable_items do
    resources :boxes do
      get "duplicate", to: "boxes#duplicate"
      post "add_with_item", to: "box_items#add_with_item"
      resources :box_items, except: %i[show edit new] do
        resources :box_unpacking_events, only: %i[create destroy]
      end
    end
  end

  concern :palletable_items do
    resources :pallets do
      post "add_with_item", to: "pallet_items#add_with_item"
      resources :pallet_items, except: %i[show edit new] do
        resources :pallet_unpacking_events, only: %i[create destroy]
      end
      concerns :boxable_items
    end
  end

  concern :containable_items do
    resources :containers do
      post "add_with_item", to: "container_items#add_with_item"
      resources :container_items, except: %i[show edit new] do
        resources :container_unpacking_events, only: %i[create destroy]
      end
      concerns :palletable_items
    end
  end

  concerns :boxable_items
  concerns :palletable_items
  concerns :containable_items
  resources :shipments do
    concerns :containable_items
  end

  # match '*unmatched', to: redirect('/404'), via: :all
end

app/controllers/box_items_controller.rb
# frozen_string_literal: true

class BoxItemsController < ApplicationController
  before_action :set_box
  before_action :set_box_item, except: %i[create index add_with_item]

  def create
    box_item = @box.box_items.build(box_item_params)

    if box_item.save
      id_sentence = box_item.show_id ? "ID: ##{box_item.id}." : ""
      message = { success: "#{box_item.quantity} #{box_item.generated_name.pluralize} added. #{id_sentence}" }
    else
      message = { error: box_item.errors.full_messages.to_sentence }
    end

    redirect_to box_box_items_path(@box), flash: message
  end

  def update
    if @box_item.update(box_item_params)
      id_sentence = @box_item.show_id ? "ID: ##{@box_item.id}." : ""
      message = { success: "#{@box_item.quantity} #{@box_item.generated_name.pluralize} updated. #{id_sentence}" }
    else
      message = { error: @box_item.errors.full_messages.to_sentence }
    end

    redirect_to box_box_items_path(@box), flash: message
  end

  def index
    @box_options = Box.reassignable
      .order(id: :desc)
      .pluck(:name, :id)
    @pallet_options = Pallet.reassignable
      .order(id: :desc)
      .pluck(:name, :id)
    @container_options = Container.in_progress
      .order(id: :desc)
      .pluck(:name, :id)
  end

  def add_with_item
    item = Item.new(item_params)
    box_item = @box.box_items.build(box_item_params.merge(item: item))

    if item.save && box_item.save
      id_sentence = box_item.show_id ? "ID: ##{box_item.id}." : ""
      message = { success: "Item created. #{box_item.quantity} #{item.generated_name.pluralize} added. #{id_sentence}" }
    else
      error_message = item.errors.full_messages + box_item.errors.full_messages
      message = { error: error_message.to_sentence }
    end

    redirect_to box_box_items_path(@box), flash: message
  end

  def destroy
    @box_item.destroy
    redirect_to box_box_items_path(@box)
  end

  private

  def box_item_params
    params.require(:packed_item).permit(:expiry_date, :quantity, :item_id, :weight, :box_id, :pallet_id, :container_id, :show_id, :status).merge(user: current_user)
  end

  def item_params
    params.require(:item)
      .permit(
        :brand, :object, :standardized_size,
        :numerical_size_1, :numerical_units_1, :numerical_description_1,
        :numerical_size_2, :numerical_units_2, :numerical_description_2,
        :area_1, :area_2, :area_units, :area_description, :range_1,
        :range_2, :range_units, :range_description, :unit_weight,
        :category_id, :notes, :verified, :photo, :flagged
      )
      .merge(user: current_user)
  end

  def set_box_item
    @box_item = PackedItem.find(params[:id])
  end

  def set_box
    @box = Box.find(params[:box_id])
  end
end

app/views/box_items/_add_new_form.html.haml
= form_for :packed_item, url: box_add_with_item_path, method: :post, html: {multipart: true, class: "new_item"} do |f|
  %h5 Use this form to simultaneously add a new item to the database and to this box. Indicate the new item's packing information in the form below.
  = render "packed_items/add_new_form_card", f: f, staged: false

app/views/box_items/_history.html.haml
- if @box.box_items.with_events.none?
  %h4.text-center
    No history
    %i.fa.fa-fw.fa-history
    to display.
- else
  %h5 Unpacking history for this box is shown here.
  = render partial: "layouts/list_quick_filter", locals: {placeholder: "Filter by name...", assoc: "history-items"}
  - @box.box_items.with_events.each do |bi|
    .row.inline-add-item
      .col-xs-12.manage-item-name
        %p
          = bi.generated_name
          - if bi.show_id
            —
            %em.show-id ID: ##{bi.id}
        .drawer-info
          %span.label.label-default= bi.quantity - bi.remaining_quantity
          %i.fa.fa-ellipsis-v
      .col-xs-12.manage-item-form.hidden
        - bi.unpacking_events.order(timestamp: :desc).each do |event|
          .unpacking-entry
            .entry-info
              %p
                %strong #{event.timestamp.strftime("%Y-%m-%d")}:
                = link_to user_path(event.user) do
                  = event.user.name
                removed #{event.quantity} #{event.quantity > 1 ? "items" : "item"}. Sent to #{event.hospital.name}.
                - unless event.notes.blank?
                  Note:
                  %em= event.notes
            .action-container
              - if current_user.admin? || current_user.receiving_manager?
                = form_for event, url: unpacking_event_path(event) do |f|
                  - timestamp = event.timestamp.strftime("%Y-%m-%d")
                  = f.text_field :timestamp, value: timestamp, placeholder: "YYYY-MM-DD", class: "form-control datepickers"
                  = submit_button_responsive("Update", "pull-right btn-xs")
                = delete_button(box_box_item_box_unpacking_event_path(@box, bi, event), "Are you sure you want to delete this unpacking entry?", "pull-right btn-xs")
        %hr
        .unpacking-entry
          .entry-info
            %p Current inventory remaining: #{bi.remaining_quantity}

app/views/box_items/_list.html.haml
- if @box.box_items.none?
  %h5.text-center This box has no items and may have been an error.
- else
  %h5 The shipping manifest for this box is shown here.
  = render partial: "layouts/list_quick_filter", locals: {placeholder: "Filter by name...", assoc: "manage-items"}
  - @box.box_items.each do |pi|
    = render "packed_items/list_card", pi: pi

app/views/box_items/_manage_form.html.haml
- if @box.box_items.none?
  %h4.text-center
    No boxed
    %i.fa.fa-fw.fa-box-open
    items.
    Use the tabs to search, or create a new item.
- else
  %h5 Update or remove existing items packed in this box.
  = render partial: "layouts/list_quick_filter", locals: {placeholder: "Filter by name or ID...", assoc: "manage-items"}
  - @box.box_items.each do |pi|
    = form_for pi, url: box_box_item_path(@box, pi) do |f|
      = render "packed_items/manage_form_card", f: f, pi: pi, path: box_box_item_path(@box, pi)

app/views/box_items/_search_form.html.haml
%h5 Search for an existing item in the database to add to this box.
.input-group.search.span12
  = hidden_field_tag :id, @box.id, id: "search-model-id"
  = hidden_field_tag :model, "Box", id: "search-model"
  .input-group
    = text_field_tag :search, params[:search], placeholder: "Begin typing to search...", class: "form-control", id: "search-params"
    %span.input-group-btn.span12#packing-search-submit
      %a.btn.btn-primary.responsive-button
        %span Search
        %i.fa.fa-search

#search-results

app/views/box_items/_unpack_form.html.haml
- if @box.box_items.with_inventory.none?
  %h4.text-center
    No items
    %i.fa.fa-fw.fa-stethoscope
    to unpack.
- else
  %h5 Unpack and remove items from this box. Items completely unpacked with no remaining quantity will not be shown here.
  = render partial: "layouts/add_hospital_modal", locals: {redirect: box_box_items_path(@box)}
  = render partial: "layouts/list_quick_filter", locals: {placeholder: "Filter by name...", assoc: "unpack-items"}
  - @box.box_items.with_inventory.each do |pi|
    = form_for :unpacking_event, url: box_box_item_box_unpacking_events_path(@box, pi) do |f|
      = render "packed_items/unpack_form_card", f: f, pi: pi

app/views/box_items/index.html.haml
.content
  .header
    %ul.breadcrumb
      %li
        = link_to "Home", index_path
      = present(@box).breadcrumbs_item
    = render partial: "layouts/jump_to_modal"
    = render partial: "layouts/mass_action_modal", locals: {name: @box.name, redirect: box_box_items_path(@box), record: nil}
  .main-content
    %ul.nav.nav-tabs
      - if can? :manage, PackedItem
        %li.active
          %a{data: {toggle: "tab"}, href: "#search"} Search
        %li
          %a{data: {toggle: "tab"}, href: "#new"} New
        %li
          %a{data: {toggle: "tab"}, href: "#manage-items"}
            Manage
            %span.label.label-success= @box.box_items.count
      - elsif cannot? :manage, PackedItem
        %li.active
          %a{data: {toggle: "tab"}, href: "#manage-items"}
            Inventory
            %span.label.label-success= @box.box_items.count
      - if can? :manage, UnpackingEvent
        %li
          %a{data: {toggle: "tab"}, href: "#unpack-items"}
            Unpack
            %span.label.label-info= @box.box_items.with_inventory.count
        %li
          %a{data: {toggle: "tab"}, href: "#history-items"}
            History
            %span.label.label-default= @box.box_items.with_events.count
    .row
      .col-xs-12
        %br
        .tab-content
          - if can? :manage, PackedItem
            #manage-items.tab-pane.fade
              = render "box_items/manage_form"

            #search.tab-pane.active.in
              = render "box_items/search_form"

            #new.tab-pane.fade
              = render "box_items/add_new_form"

          - elsif cannot? :manage, PackedItem
            #manage-items.tab-pane.active.in
              = render "box_items/list"

          - if can? :manage, UnpackingEvent
            #unpack-items.tab-pane.fade
              = render "box_items/unpack_form"

            #history-items.tab-pane.fade
              = render "box_items/history"