config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "sessions#index", as: :index

  get "/privacy", to: static("privacy.html")
  get "/terms", to: static("terms.html")
  get "/admin_help", to: static("admin_help.html")
  get "/volunteer_help", to: static("volunteer_help.html")
  get "/dev_updates", to: static("dev_updates.html")
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  get "my_activity", to: "sessions#my_activity"

  get "signup", to: "users#signup"
  post "create_public_user", to: "users#create_public_user"

  get "reconcile_item_search", to: "items#reconcile_search"
  get "item_search_form", to: "items#search_form"
  get "index_item_search", to: "items#index_search"
  get "unverified_item_search", to: "items#unverified_search"
  get "uncategorized_item_search", to: "items#uncategorized_search"
  get "packed_item_search", to: "items#packed_search"
  get "reconcile_unverified", to: "reconcile_items#unverified"
  get "reconcile_uncategorized", to: "reconcile_items#uncategorized"
  get "reconcile_flagged", to: "reconcile_items#flagged"
  get "reconcile/:id", to: "reconcile_items#start", as: :reconcile_start
  post "reconcile/:id", to: "reconcile_items#confirm", as: :reconcile_confirm
  post "reconcile/:id/execute_reconcile", to: "reconcile_items#execute", as: :execute_reconcile
  get "reconcile/:id/item_instances", to: "reconcile_items#item_instances", as: :item_instances
  post "find_box", to: "boxes#find"
  post "find_pallet", to: "pallets#find"
  post "mass_action", to: "mass_actions#mass_action"
  get "all_received_items", to: "packed_items#all_received_items"
  get "received_categories", to: "packed_items#received_categories"
  get "received_categories/:id/received_category_items", to: "packed_items#received_category_items", as: :received_category_items
  get "received_category_items/:id/received_item_locations", to: "packed_items#received_item_locations", as: :received_item_locations
  get "received_categories/uncategorized", to: "packed_items#received_uncategorized_items", as: :received_uncategorized_items
  post "received_categories/unpack_selected", to: "packed_items#unpack_selected"

  resources :unpacking_events, only: %i[index update]
  resources :hospital_exports, only: :create
  resources :shipment_exports, only: :create
  resources :unpacking_events_exports, only: :create
  resources :categories
  resources :items
  resources :users do
    member do
      patch :change_password
    end
  end
  resources :warehouses
  resources :hospitals
  resources :packed_items, only: :index
  resources :staged_items
  post "staged_item_add_with_item", to: "staged_items#add_with_item"
  resources :warehoused_items
  post "warehoused_item_add_with_item", to: "warehoused_items#add_with_item"
  post "boxes/:id/unpack_all", to: "boxes#unpack_all", as: "boxes_unpack_all"
  post "pallets/:id/unpack_all", to: "pallets#unpack_all", as: "pallets_unpack_all"

  concern :boxable_items do
    resources :boxes do
      get "duplicate", to: "boxes#duplicate"
      post "add_with_item", to: "box_items#add_with_item"
      resources :box_items, except: %i[show edit new] do
        resources :box_unpacking_events, only: %i[create destroy]
      end
    end
  end

  concern :palletable_items do
    resources :pallets do
      post "add_with_item", to: "pallet_items#add_with_item"
      resources :pallet_items, except: %i[show edit new] do
        resources :pallet_unpacking_events, only: %i[create destroy]
      end
      concerns :boxable_items
    end
  end

  concern :containable_items do
    resources :containers do
      post "add_with_item", to: "container_items#add_with_item"
      resources :container_items, except: %i[show edit new] do
        resources :container_unpacking_events, only: %i[create destroy]
      end
      concerns :palletable_items
    end
  end

  concerns :boxable_items
  concerns :palletable_items
  concerns :containable_items
  resources :shipments do
    concerns :containable_items
  end

  # match '*unmatched', to: redirect('/404'), via: :all
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  belongs_to :user, optional: false

  has_many :items
  has_many :pallets

  paginates_per 25
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :set_category, only: %i[show destroy update]

  def new
    @category = Category.new
  end

  def create
    category = Category.new(category_params.merge(user: current_user))

    if category.save
      redirect_to category_path(category), flash: { success: "Category created." }
    else
      redirect_to categories_path,
                  flash: { error: "Failed to create new category: #{category.errors.full_messages.to_sentence}" }
    end
  end

  def index
    @categories = Category.all.order(:name).page params[:page]
  end

  def show
  end

  def update
    if @category.update(category_params)
      redirect_to category_path(@category), flash: { success: "Category updated." }
    else
      redirect_to category_path(@category),
                  flash: { error: "Failed to update category: #{@category.errors.full_messages.to_sentence}" }
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, flash: { success: "Category deleted." }
  end

  private

  def category_params
    params.require(:category).permit(:name, :description)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  .col-xs-12.col-sm-4
    .form-group
      %label Name
      = f.text_field :name, class: "form-control"
  .col-xs-12.col-sm-8
    .form-group
      %label Description
      = f.text_field :description, class: "form-control"

  .col-xs-12
    .btn-toolbar.list-toolbar
      - if @category.persisted? && @category.items.none?
        = delete_button(category_path(@category), "Are you sure you want to delete #{@category.name}? This cannot be reversed")
      = submit_button_responsive("Save")

app/views/categories/index.html.haml
.content
  .header
    %ul.breadcrumb
      %li
        = link_to "Home", index_path
      %li.active Categories
    = render partial: "layouts/jump_to_modal"
    = add_button(new_category_path, "Category", "fa-file-medical")
  .main-content
    %table.table.table-striped.table-hover.link-rows
      %thead
        %tr
          %th Name
          %th.hidden-xs Description
      %tbody
        - @categories.each do |category|
          %tr
            %td
              = link_to category_path(category) do
                %p= category.name
            %td.hidden-xs
              = link_to category_path(category) do
                %p= category.description

    = paginate @categories, window: 2

app/views/categories/new.html.haml
.content
  .header
    %ul.breadcrumb
      %li
        = link_to "Home", index_path
      %li
        = link_to "Categories", categories_path
      %li.active New Category
    = render partial: "layouts/jump_to_modal"
  .main-content
    .row
      %br
      = render partial: "form"

app/views/categories/show.html.haml
.content
  .header
    %ul.breadcrumb
      %li
        = link_to "Home", index_path
      %li
        = link_to "Categories", categories_path
      %li.active= @category.name
    = render partial: "layouts/jump_to_modal"
    = render partial: "layouts/edit_modal"
  .main-content
    .row
      .col-xs-12
        %h5.text-muted Name
        %h4= @category.name
        %hr
      - if @category.description.present?
        .col-xs-12
          %h6.text-muted Description
          %h5= @category.description
      .col-lg-3.col-sm-4.col-xs-6
        = link_to items_path(category: @category.id) do
          %h6.text-muted
            Items with this Category
            %i.fa.fa-search
          %h5= @category.items.count
      .col-lg-3.col-sm-4.col-xs-6
        %h6.text-muted Created By
        %h5= @category.user.name
      .col-lg-3.col-sm-4.col-xs-6
        %h6.text-muted Created At
        %h5= @category.created_at.strftime("%Y-%m-%d")